plugins {
	id 'java'
	id 'application'
}
group = 'pt.upt.softwarequality'
version = '1.0.0'
repositories {
	mavenCentral()
}
application {
	mainClass = 'pt.upt.fleetcheck.App'
}
java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}
dependencies {
	testImplementation 'org.junit.jupiter:junit-jupiter:5.14.4'
	implementation 'com.fasterxml.jackson.core:jackson-databind:2.22.2'
}
test {
	useJUnitPlatform()
}
jar {
	manifest {
		attributes 'Main-Class': 'pt.upt.fleetcheck.App'
	}
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
	from {
		configurations.runtimeClasspath.collect {
			it.isDirectory() ? it : zipTree(it)
		}
	}
}
